### ISSUE TITLE
template tag in class body fails

### ISSUE THREAD

**Issue by simonihmig** [NullVoxPopuli/polaris-starter#10]
## Reproduction
* change excite.gts to be class-based
* see https://stackblitz.com/edit/github-d5nz5f?file=app%2Fcomponents%2Fexcite.gts

## Result
![image](https://github.com/NullVoxPopuli/polaris-starter/assets/1325249/fa6cfe6e-b766-4bac-9c28-df00374bfc67)

**Comment by NullVoxPopuli** [comment]
Blocked by: 
- https://github.com/typed-ember/glint/pull/615
- https://github.com/typed-ember/glint/issues/609

**Comment by NullVoxPopuli** [comment]
This is resolved :tada:
