### ISSUE TITLE
404 not found on https://polaris-starter.pages.dev/

### ISSUE THREAD

**Issue by johanrd** [NullVoxPopuli/polaris-starter#14]
https://polaris-starter.pages.dev/ returns `Error 404 not found`

Expected from [readme.md#16](https://github.com/NullVoxPopuli/polaris-starter/blob/main/README.md?plain=1#L16):
```md
The demo app contained in this repo is deployed here: https://polaris-starter.pages.dev/
```

**Comment by NullVoxPopuli** [comment]
Aye, that's due to: https://github.com/embroider-build/embroider/issues/1595

I should probably deploy the `webpack` branch instead for now

**Comment by NullVoxPopuli** [comment]
fixed! thanks!

**Comment by johanrd** [comment]
wow, great, thanks:rocket:
